services:
  # A web service for the FastAPI application
  - type: web
    name: job-finder-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: USE_MOCK_SCRAPERS
        value: False
      - key: USE_FALLBACK_FILTERING
        value: True
      - key: USE_API_EMULATION
        value: True
      - key: USE_RESIDENTIAL_PROXIES
        value: True
